package com.digitaltwin.backend.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.Map;

@Document("twin_profiles")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TwinProfile {

    @Id
    private String id;

    private String userId; // Reference to the User who owns this profile

    private Map<Integer, String> profileAnswers; // User's answers to profile questions

    private String profileSummary; // Generated by AI

    private LocalDateTime createdAt;
}
